DotNet.Highcharts.Samples/Controllers/HoTosController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Samples.Models;
using Chart = DotNet.Highcharts.Options.Chart;
using Point = DotNet.Highcharts.Options.Point;

namespace DotNet.Highcharts.Samples.Controllers
{
    public class HoTosController : Controller
    {
        public ActionResult MultipleXAxes()
        {
            // Example from JSFIDDLE: http://jsfiddle.net/kSkYN/4502/

            Highcharts chart = new Highcharts("chart")
                .SetTitle(new Title { Text = "Multiple X-Axes" })
                .SetXAxis(new[]
                          {
                              new XAxis { Type = AxisTypes.Datetime },
                              new XAxis { Type = AxisTypes.Datetime, Opposite = true }
                          })
                .SetSeries(new[]
                           {
                               new Series
                               {
                                   Data = new Data(new object[] { 29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4 }),
                                   PlotOptionsSeries = new PlotOptionsSeries
                                                       {
                                                           PointStart = new PointStart(new DateTime(2010, 1, 1)),
                                                           PointInterval = 24 * 3600 * 1000 // one day
                                                       }
                               },
                               new Series
                               {
                                   Data = new Data(new object[] { 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4, 29.9, 71.5, 106.4, 129.2, 144.0 }),
                                   PlotOptionsSeries = new PlotOptionsSeries
                                                       {
                                                           PointStart = new PointStart(new DateTime(2010, 1, 10)),
                                                           PointInterval = 24 * 3600 * 1000, // one day
                                                       },
                                   XAxis = "1"
                               }
                           });

            return View(chart);
        }

        public ActionResult ChartInFunction()
        {
            Highcharts chart = new Highcharts("newChart")
                .SetTitle(new Title { Text = "Chart inside JavaScript function" })
                .SetTooltip(new Tooltip { Formatter = "function() { return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %'; }" })
                .SetXAxis(new XAxis { Categories = new[] { "Apples", "Oranges", "Pears", "Bananas", "Plums" } })
                .SetTooltip(new Tooltip { Formatter = "TooltipFormatter" })
                .SetLabels(new Labels
                           {
                               Items = new[]
                                       {
                                           new LabelsItems
                                           {
                                               Html = "Total fruit consumption",
                                               Style = "left: '40px', top: '8px', color: 'black'"
                                           }
                                       }
                           })
                .SetPlotOptions(new PlotOptions
                                {
                                    Pie = new PlotOptionsPie
                                          {
                                              Center = new[] { new PercentageOrPixel(100), new PercentageOrPixel(80) },
                                              Size = new PercentageOrPixel(100),
                                              ShowInLegend = false,
                                              DataLabels = new PlotOptionsPieDataLabels { Enabled = false }
                                          }
                                })
                .SetSeries(new[]
                           {
                               new Series
                               {
                                   Type = ChartTypes.Column,
                                   Name = "Jane",
                                   Data = new Data(new object[] { 3, 2, 1, 3, 4 })
                               },
                               new Series
                               {
                                   Type = ChartTypes.Column,
                                   Name = "John",
                                   Data = new Data(new object[] { 2, 3, 5, 7, 6 })
                               },
                               new Series
                               {
                                   Type = ChartTypes.Column,
                                   Name = "Joe",
                                   Data = new Data(new object[] { 4, 3, 3, 9, 0 })
                               },
                               new Series
                               {
                                   Type = ChartTypes.Spline,
                                   Name = "Average",
                                   Data = new Data(new object[] { 3, 2.67, 3, 6.33, 3.33 })
                               },
                               new Series
                               {
                                   Type = ChartTypes.Pie,
                                   Name = "Total consumption",
                                   Data = new Data(new[]
                                                   {
                                                       new Point
                                                       {
                                                           Name = "Jane",
                                                           Y = 13,
                                                           Color = Color.FromName("colors[5]")
                                                       },
                                                       new Point
                                                       {
                                                           Name = "John",
                                                           Y = 23,
                                                           Color = Color.FromName("colors[6]")
                                                       },
                                                       new Point
                                                       {
                                                           Name = "Joe",
                                                           Y = 19,
                                                           Color = Color.FromName("colors[7]")
                                                       }
                                                   }
                                       )
                               }
                           })
                .InFunction("DrawChart")
                .AddJavascripVariable("colors", "Highcharts.getOptions().colors")
                .AddJavascripFunction("TooltipFormatter",
                                      @"var s;
                    if (this.point.name) { // the pie chart
                       s = ''+
                          this.point.name +': '+ this.y +' fruits';
                    } else {
                       s = ''+
                          this.x  +': '+ this.y;
                    }
                    return s;");

            return View(chart);
        }

        public ActionResult MultipleCharts()
        {
            Highcharts chart1 = new Highcharts("chart1")
                .InitChart(new Chart { Type = ChartTypes.Column })
                .SetTitle(new Title { Text = "Chart 1" })
                .SetXAxis(new XAxis
                          {
                              Categories = new[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }
                          })
                .SetSeries(new Series
                           {
                               Data = new Data(new object[] { 29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4 })
                           });

            Highcharts chart2 = new Highcharts("chart2")
                .InitChart(new Chart { Type = ChartTypes.Bar })
                .SetTitle(new Title { Text = "Chart 2" })
                .SetXAxis(new XAxis
                          {
                              Categories = new[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }
                          })
                .SetSeries(new Series
                           {
                               Data = new Data(new object[] { 29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4 })
                           })
                .InFunction("DrawChart2");

            Highcharts chart3 = new Highcharts("chart3")
                .InitChart(new Chart { Type = ChartTypes.Spline })
                .SetTitle(new Title { Text = "Chart 3" })
                .SetXAxis(new XAxis
                          {
                              Categories = new[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }
                          })
                .SetSeries(new Series
                           {
                               Data = new Data(new object[] { 29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4 })
                           })
                .InFunction("DrawChart3");

            Highcharts chart4 = new Highcharts("chart4")

DotNet.Highcharts.Samples/Views/Shared/_HowTosLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/themes/start/jquery-ui-1.10.3.custom.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Scripts/prettify-small-1-Jun-2011/google-code-prettify/prettify.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-2.0.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/highcharts-all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/modules/funnel.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/core.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/prettify-small-1-Jun-2011/google-code-prettify/prettify.js")" type="text/javascript"></script>
</head>
<body onload="prettyPrint()">
    <div class="page">
        <header>
            <div id="title">
                <h1>DotNet.Highcharts</h1>
            </div>
            <div id="logindisplay">
                &nbsp;
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Demo", "BasicLine", "Demo")</li>
                    <li>@Html.ActionLink("How To's", "MultipleXAxes", "HoTos")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            <div style="float: left; width: 20%">
                <div id="accordion">
                    <h3>
                        <a href="#">How tos</a>
                    </h3>
                    <div data-panel-index="0">
                        @Html.ActionLink("Multiple X-Axes", "MultipleXAxes", "HoTos")
                        @Html.ActionLink("Chart inside JavaScript function", "ChartInFunction", "HoTos")
                        @Html.ActionLink("Multiple charts in one page", "MultipleCharts", "HoTos")
                        @Html.ActionLink("Disable Animation", "DisableAnimation", "HoTos")
                        @Html.ActionLink("EaseOutBounce Effect", "EaseOutBounceEffect", "HoTos")
                        @Html.ActionLink("Bind Decimal Values", "BindDecimalValues", "HoTos")
                        @Html.ActionLink("Use .NET Globalization", "UseDotNetGlobalization", "HoTos")
                        @Html.ActionLink("Bind Data From Dictionary", "BindDataFromDictionary", "HoTos")
                        @Html.ActionLink("Bind Data From Object List", "BindDataFromObjectList", "HoTos")
                        @Html.ActionLink("Custom Theme", "CustomTheme", "HoTos")
                        @Html.ActionLink("Tooltip Crosshairs", "TooltipCrosshairs", "HoTos")
                        @Html.ActionLink("Crosshairs With Boolean Values", "CrosshairsWithBooleanValues", "HoTos")
                        @Html.ActionLink("Theming The Reset Button", "ThemingTheResetButton", "HoTos")
                        @Html.ActionLink("Plot Band Events", "PlotBandEvents", "HoTos")
                        @Html.ActionLink("Transparent Background", "TransparentBackground", "HoTos")
                        @Html.ActionLink("Pie Chart With Events", "PieChartWithEvents", "HoTos")
                        @Html.ActionLink("Click Event on Series Point with URL", "SeriesPointEventsClickUrl", "HoTos")
                        @Html.ActionLink("Columns with datetime", "ColumnWithDatetime", "HoTos")
                        @Html.ActionLink("Split chart container and Javascript", "SplitChartContainerAndJavascript", "HoTos")
                        @Html.ActionLink("Point name as text for number", "PointNameAsTextForNumber", "HoTos")
                    </div>
                </div>
            </div>
            <div style="float: left; width: 79%; padding-left: 10px">
                @RenderBody()
            </div>
            <div style="clear: both">
            </div>
        </section>
        <footer></footer>
    </div>
    @RenderSection("JavaScripts", required: false)
</body>
</html>

DotNet.Highcharts.Samples/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/themes/start/jquery-ui-1.10.3.custom.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Scripts/prettify-small-1-Jun-2011/google-code-prettify/prettify.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-2.0.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/highcharts-all.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/modules/funnel.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/modules/solid-gauge.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Highcharts-4.0.1/js/modules/drilldown.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/core.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/prettify-small-1-Jun-2011/google-code-prettify/prettify.js")" type="text/javascript"></script>
</head>
<body onload="prettyPrint()">
    <div class="page">
        <header>
            <div id="title">
                <h1>DotNet.Highcharts</h1>
            </div>
            <div id="logindisplay">
                &nbsp;
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Demo", "BasicLine", "Demo")</li>
                    <li>@Html.ActionLink("How To's", "MultipleXAxes", "HoTos")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            <div style="float: left; width: 20%">
                <div id="accordion">
                    <h3>
                        <a href="#">Line charts</a>
                    </h3>
                    <div data-panel-index="0">
                        @Html.ActionLink("Basic Line", "BasicLine", "Demo")
                        @Html.ActionLink("Ajax loaded data, clickable points", "AjaxLoad", "Demo")
                        @Html.ActionLink("With data labels", "DataLabels", "Demo")
                        @Html.ActionLink("Time series, zoomable", "TimeSeriesZoomable", "Demo")
                        @Html.ActionLink("Spline with inverted axes", "SplineInvertedAxes", "Demo")
                        @Html.ActionLink("Spline with symbols", "SplineWithSymbols", "Demo")
                        @Html.ActionLink("Spline with plot bands", "SplineWithPlotBands", "Demo")
                        @Html.ActionLink("Time data with inrregular intervals", "TimeDataWithInrregularIntervals", "Demo")
                        @Html.ActionLink("Logarithmic Axis", "LogarithmicAxis", "Demo")
                    </div>
                    <h3>
                        <a href="#">Area charts</a>
                    </h3>
                    <div data-panel-index="1">
                        @Html.ActionLink("Basic area", "BasicArea", "Demo")
                        @Html.ActionLink("Area with negative values", "AreaWithNegativeValues", "Demo")
                        @Html.ActionLink("Stacked area", "StackedArea", "Demo")
                        @Html.ActionLink("Percentage area", "PercentageArea", "Demo")
                        @Html.ActionLink("Area with missing points", "AreaWithMissingPoints", "Demo")
                        @Html.ActionLink("Inverted axes", "InvertedAxes", "Demo")
                        @Html.ActionLink("Area-spline", "AreaSpline", "Demo")
                        @Html.ActionLink("Area Range Chart", "AreaRangeChart", "Demo")
                        @Html.ActionLink("Area Range and Line", "AreaRangeAndLine", "Demo")
                    </div>
                    <h3>
                        <a href="#">Column and bar charts</a>
                    </h3>
                    <div data-panel-index="2">
                        @Html.ActionLink("Basic bar", "BasicBar", "Demo")
                        @Html.ActionLink("Stacked bar", "StackedBar", "Demo")
                        @Html.ActionLink("Bar with negotive stack", "BarWithNegotiveStack", "Demo")
                        @Html.ActionLink("Basic column", "BasicColumn", "Demo")
                        @Html.ActionLink("Column with negative values", "ColumnWithNegativeValues", "Demo")
                        @Html.ActionLink("Stacked column", "StackedColumn", "Demo")
                        @Html.ActionLink("Stacked and grouped column", "StackedAndGroupedColumn", "Demo")
                        @Html.ActionLink("Stacked percentage column", "StackedPercentageColumn", "Demo")
                        @Html.ActionLink("Column with rotated labels", "ColumnWithRotatedLabels", "Demo")
                        @Html.ActionLink("Column with drilldown", "ColumnWithDrilldown", "Demo")
                        @Html.ActionLink("Column Range", "ColumnRange", "Demo")
                        @Html.ActionLink("Fixed Placement Columns", "FixedPlacementColumns", "Demo")
                    </div>
                    <h3>
                        <a href="#">Pie charts</a>
                    </h3>
                    <div data-panel-index="3">
                        @Html.ActionLink("Pie chart", "PieChart", "Demo")
                        @Html.ActionLink("Pie with gradient fill", "PieWithGradientFill", "Demo")
                        @Html.ActionLink("Pie With Monochrome Fill", "PieWithMonochromeFill", "Demo")
                        @Html.ActionLink("Donut chart", "DonutChart", "Demo")
                        @Html.ActionLink("Semi Circle Donut", "SemiCircleDonut", "Demo")
                        @Html.ActionLink("Pie with drilldown", "PieWithDrilldown", "Demo")
                        @Html.ActionLink("Pie with legend", "PieWithLegend", "Demo")
                    </div>
                    <h3>
                        <a href="#">Scatter and bubble charts</a>
                    </h3>
                    <div data-panel-index="4">
                        @Html.ActionLink("Scatter Plot", "ScatterPlot", "Demo")
                        @Html.ActionLink("Bubble Chart", "BubbleChart", "Demo")
                        @Html.ActionLink("Bubbles 3D", "Bubbles3D", "Demo")
                    </div>
                    <h3>
                        <a href="#">Dynamic charts</a>
                    </h3>
                    <div data-panel-index="5">
                        @Html.ActionLink("Spline update each second", "SplineUpdateEachSecond", "Demo")
                        @Html.ActionLink("Click to add a point", "ClickToAddPoint", "Demo")
                    </div>
                    <h3>
                        <a href="#">Combinations</a>
                    </h3>
                    <div data-panel-index="6">
                        @Html.ActionLink("Column, line and pie", "ColumnLineAndPie", "Demo")
                        @Html.ActionLink("Dual axes, line and column", "DualAxesLineAndColumn", "Demo")
                        @Html.ActionLink("Multiple axes", "MultipleAxes", "Demo")
                        @Html.ActionLink("Scatter plot with regression line", "ScatterPlotWithRegressionLine", "Demo")
                    </div>
                    <h3>
                        <a href="#">3D Charts</a>
                    </h3>
                    <div data-panel-index="7">
                        @Html.ActionLink("3D Column", "ThreeDColumn", "Demo")
                        @Html.ActionLink("3D Column With Null And 0 Values", "ThreeDColumnWithNullAndZeroValues", "Demo")
                        @Html.ActionLink("3D Column With Stacking And Grouping", "ThreeDColumnWithStackingAndGrouping", "Demo")
                        @Html.ActionLink("3D Pie", "ThreeDPie", "Demo")
                        @Html.ActionLink("3D Donut", "ThreeDDonut", "Demo")
                    </div>
                    <h3>
                        <a href="#">Gauges</a>
                    </h3>
                    <div data-panel-index="8">
                        @Html.ActionLink("Angular Gauge", "AngularGauge", "Demo")
                        @Html.ActionLink("Gauge With Dual Axes", "GaugeWithDualAxes", "Demo")
                        @Html.ActionLink("Solid Gauge", "SolidGauge", "Demo")
                    </div>
                    <h3>
                        <a href="#">More chart types</a>
                    </h3>
                    <div data-panel-index="9">
                        @Html.ActionLink("Polar Chart", "PolarChart", "Demo")
                        @Html.ActionLink("Speederweb", "Speederweb", "Demo")
                        @Html.ActionLink("Box Plot", "BoxPlot", "Demo")
                        @Html.ActionLink("Waterfall", "Waterfall", "Demo")
                        @Html.ActionLink("Funnel", "Funnel", "Demo")
                    </div>
                </div>
            </div>
            <div style="float: left; width: 79%; padding-left:10px">
                @RenderBody()
            </div>
            <div style="clear: both">
            </div>
        </section>
        <footer></footer>
    </div>
</body>
</html>